version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Visual Studio 2019

configuration:
- Release
- Debug

platform:
- x64
#- x86 # by design PS4Delta can't support x86 systems

install:
- cmd: |
    git submodule update --init --recursive
    set QT_DIR=C:\Qt\5.14.0\msvc2017_64
    pmake.bat

build:
  project: build/PS4Delta.sln
  parallel: true
  verbosity: minimal

test: off
