version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Ubuntu
- Visual Studio 2019

configuration:
#- Release
- Debug

platform:
- x64
#- x86 # by design PS4Delta can't support x86 systems

environment:
  qt_email:
    secure: J54FJzRIHqrCTjqRjZzFiQ==
  qt_password:
    secure: KTGAtqdpX0CeX1iGXIiY7A==

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - |
      git submodule update --init --recursive
      set QT_DIR=C:\Qt\5.14.0\msvc2017_64
      pmake.bat
      type build\delta-qt.vcxproj
  build:
    project: build/PS4Delta.sln
    parallel: true
    verbosity: minimal
  after_build:
    - 7z a Artifacts.zip .\bin\*
  artifacts:
    - path: Artifacts.zip

-
  matrix:
    only:
      - image: Ubuntu
  install:
    - |
      git submodule update --init --recursive
      cat ../ps4delta/tools/install_qt.qs | sed 's/email_address/'"$qt_email"'/g' | sed 's/your_password/'"$qt_password"'/g' > ../ps4delta/tools/install_qt_filled.qs
      curl -fsS -o qt.run http://master.qt.io/archive/online_installers/3.2/qt-unified-linux-x64-3.2.1-online.run
      chmod +x qt.run
      ./qt.run --script ./tools/install_qt_filled.qs --platform minimal
      sudo apt-get update && sudo apt install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev mesa-common-dev
      ls ~/Qt/5.14.1/gcc_64/
      export QT_DIR=~/Qt/5.14.1/gcc_64
      export QT_INCLUDE=~/Qt/5.14.1/gcc_64/include
      export QT_BIN=~/Qt/5.14.1/gcc_64/bin
      chmod +x ./pmake.sh
      ./pmake.sh
      md5sum ./tools/premake/bin/linux/premake5
      ./tools/premake/bin/linux/premake5 --version
  build_script:
    - |
      echo `pwd`
      cd build
      echo `pwd`
      cd ..
      echo `pwd`
      cd code
      echo `pwd`
      cd delta_qt
      echo `pwd`
      cd qtgen
      echo `pwd`
      ldd ~/Qt/5.14.1/gcc_64/bin/uic
      ldd ~/Qt/5.14.1/gcc_64/bin/moc
      echo `pwd`
      ls
      ~/Qt/5.14.1/gcc_64/bin/uic -o "../code/delta_qt/qtgen/ui_mainwindow.h" "../code/delta_qt/ui/mainwindow.ui"
      ls -la ../code/delta_qt/qtgen/
      echo `pwd`
      cat ../code/delta_qt/qtgen/ui_mainwindow.h
      cat ./delta-qt.make
      if [ "$CONFIGURATION" = "Release" ]; then
        make config=release
      else
        make config=debug
      fi

test: off
