version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
- Ubuntu
- Visual Studio 2019

configuration:
#- Release
- Debug

platform:
- x64
#- x86 # by design PS4Delta can't support x86 systems

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - |
      git submodule update --init --recursive
      set QT_DIR=C:\Qt\5.14.0\msvc2017_64
      pmake.bat
      type build\delta-qt.vcxproj
  build:
    project: build/PS4Delta.sln
    parallel: true
    verbosity: minimal
  after_build:
    - 7z a Artifacts.zip .\bin\*
  artifacts:
    - path: Artifacts.zip

-
  matrix:
    only:
      - image: Ubuntu
  install:
    - |
      git submodule update --init --recursive
      wget -c http://master.qt.io/archive/online_installers/3.2/qt-unified-linux-x64-3.2.1-online.run -o qt.run
      chmod +x qt.run
      ./qt.run --verbose --script ./tools/install_qt.qs
      sudo apt-get update && sudo apt install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev mesa-common-dev
      ls ~/Qt
      ls ~/Qt/5.14.1/gcc_64/
      export QT_DIR=~/Qt/5.14.1/gcc_64/lib
      export QT_INCLUDE=~/Qt/5.14.1/gcc_64/include
      export QT_BIN=~/Qt/5.14.1/gcc_64/bin
      chmod +x ./pmake.sh
      ./pmake.sh
      md5sum ./tools/premake/bin/linux/premake5
      ./tools/premake/bin/linux/premake5 --version
  build_script:
    - |
      cd build
      which moc
      ls
      cat ./delta-qt.make
      if [ "$CONFIGURATION" = "Release" ]; then
        make config=release
      else
        make config=debug
      fi

test: off
